run:
  timeout: 5m
  output:
    format: tab
  skip-dirs:
    - vendor
  go: '1.17'

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.1
  dupl:
    threshold: 100
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
      - diagnostic
    settings:
      hugeParam:
        sizeThreshold: 512


linters:
  enable:
    - dupl
    - exportloopref
    - gas
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - revive
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
  fast: false
  disable-all: true

issues:
  exclude-rules:
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - golint
    - path: _test\.go
      linters:
        - gosec
        - dupl

service:
  golangci-lint-version: 1.50.x
