name: Go

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: run tests
        run: go test -v -timeout=100s ./...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.50
